name: Debian Build

on: [push]

jobs:
  build:

    runs-on: debian-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7.6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install and run
      run: |
        cd ./servers
        python3 -m venv venv
        source venv/bin/activate
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        python3 -m fbs freeze
        cd ..
        sudo apt-get install zip
        mkdir dist
        mkdir dist/build
        mkdir dist/build/ExtensibleClipboard
        cp -r ./servers/target/ExtensibleClipboard ./
        zip -r ./dist/release.zip ./ExtensibleClipboard
    - name: Archive build
      uses: actions/upload-artifact@v1
      with:
        name: Release
        path: dist/release.zip
